apiVersion: apps/v1
kind: Deployment 
metadata:
  name: java-example
spec:
  selector:
    matchLabels:
      app: java-example
  replicas: 2 
  template:
    metadata:
      labels:
        app: java-example
    spec:
      serviceAccountName: veena
      imagePullSecrets:
        - name: ecr-new-key
      containers:
        - name: java-example
          image: 209479277669.dkr.ecr.ap-south-1.amazonaws.com/sept-2024:java-example
          command: ["/bin/sh","-c","sleep infinity"]
          imagePullPolicy: Always
          ports:
            - containerPort: 80
