apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javaapp-deployment
spec:
  selector:
    matchLabels:
      app: javaapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      imagePullSecrets:
        - name: ecr-key
      containers:
        - name: javaapp
          image: 209479277669.dkr.ecr.ap-south-1.amazonaws.com/sept-2024:java-example
          imagePullPolicy: Always
          ports:
            - containerPort: 80
